[32mINFO    [0m sqlalchemy.engine.Engine:base.py:2689 BEGIN (implicit)
[32mINFO    [0m sqlalchemy.engine.Engine:base.py:1848 INSERT INTO bookmazon.password_reset_tokens (user_email, token, token_status, update_datetime, create_datetime) VALUES (%(user_email)s, %(token)s, %(token_status)s, %(update_datetime)s, %(create_datetime)s) RETURNING bookmazon.password_reset_tokens.id
[32mINFO    [0m sqlalchemy.engine.Engine:base.py:1848 [cached since 0.4421s ago] {'user_email': '111423059@cc.ncu.edu.tw', 'token': 'xGrEw2X5903U0xMpVkvaKq-v6H8ZuOTQG3Nqs5wusvE', 'token_status': '1', 'update_datetime': datetime.datetime(2023, 12, 20, 16, 19, 6, 986545), 'create_datetime': datetime.datetime(2023, 12, 20, 16, 14, 6, 986545)}
[32mINFO    [0m sqlalchemy.engine.Engine:base.py:2692 ROLLBACK
[31m[1mERROR   [0m C:\Users\user\PycharmProjects\pythonProject\bookmazon\utils\logger.py:UserService.py:382 Failed to save password reset token to database: (psycopg2.errors.UndefinedTable) relation "bookmazon.password_reset_tokens" does not exist
LINE 1: INSERT INTO bookmazon.password_reset_tokens (user_email, tok...
                    ^

[SQL: INSERT INTO bookmazon.password_reset_tokens (user_email, token, token_status, update_datetime, create_datetime) VALUES (%(user_email)s, %(token)s, %(token_status)s, %(update_datetime)s, %(create_datetime)s) RETURNING bookmazon.password_reset_tokens.id]
[parameters: {'user_email': '111423059@cc.ncu.edu.tw', 'token': 'xGrEw2X5903U0xMpVkvaKq-v6H8ZuOTQG3Nqs5wusvE', 'token_status': '1', 'update_datetime': datetime.datetime(2023, 12, 20, 16, 19, 6, 986545), 'create_datetime': datetime.datetime(2023, 12, 20, 16, 14, 6, 986545)}]
(Background on this error at: https://sqlalche.me/e/20/f405)
[31m[1mERROR   [0m C:\Users\user\PycharmProjects\pythonProject\bookmazon\utils\logger.py:UserService.py:356 Error generating reset token: (psycopg2.errors.UndefinedTable) relation "bookmazon.password_reset_tokens" does not exist
LINE 1: INSERT INTO bookmazon.password_reset_tokens (user_email, tok...
                    ^

[SQL: INSERT INTO bookmazon.password_reset_tokens (user_email, token, token_status, update_datetime, create_datetime) VALUES (%(user_email)s, %(token)s, %(token_status)s, %(update_datetime)s, %(create_datetime)s) RETURNING bookmazon.password_reset_tokens.id]
[parameters: {'user_email': '111423059@cc.ncu.edu.tw', 'token': 'xGrEw2X5903U0xMpVkvaKq-v6H8ZuOTQG3Nqs5wusvE', 'token_status': '1', 'update_datetime': datetime.datetime(2023, 12, 20, 16, 19, 6, 986545), 'create_datetime': datetime.datetime(2023, 12, 20, 16, 14, 6, 986545)}]
(Background on this error at: https://sqlalche.me/e/20/f405)